# Generated by Django 4.0.3 on 2022-04-10 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.TextField(default=1, verbose_name='Category'),
            preserve_default=False,
        ),
    ]
